name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Zip the three packs if those folders exist inside the project dir
      - name: Ensure release assets (zip project folders)
        working-directory: OfficialElevenLabsPaLM
        run: |
          set -e
          for d in "ElevenLabs_Batch_Helper_and_ProClone_v1" \
                   "Official_ElevenLabs_PaLM_v1" \
                   "Official_ElevenLabs_PaLM_CI_Addon_v1"
          do
            if [ -d "$d" ]; then
              if [ ! -f "${d}.zip" ]; then
                zip -r "${d}.zip" "$d"
              fi
            fi
          done
          ls -la

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            OfficialElevenLabsPaLM/ElevenLabs_Batch_Helper_and_ProClone_v1.zip
            OfficialElevenLabsPaLM/Official_ElevenLabs_PaLM_v1.zip
            OfficialElevenLabsPaLM/Official_ElevenLabs_PaLM_CI_Addon_v1.zip
